
# Sudoku
# Inteligência Artificial - Professor Favan
# Geísa e Fabrício

In [2]:
# Importação das bibliotecas.
import random
import numpy

In [6]:
# Função apenas pra deixar o print do tabuleiro bonito,
# pode usar apenas o numpy para mostrar a matriz organizada
def Printgrid(Grid):
    TableTB = "|--------------------------------|"
    TableMD = "|----------+----------+----------|"
    print(TableTB)
    for x in range(9):
        for y in range(9):
            if ((x == 3 or x == 6) and y == 0):
                print(TableMD)
            if (y == 0 or y == 3 or y== 6):
                print("|", end=" ")
            print(" " + str(Grid[x][y]), end=" ")
            if (y == 8):
                print("|")
    print(TableTB)

<p><b> AMBIENTE </b></p>

In [4]:
# Criando tabuleiro gerado aleatoriamente

def gera_sudoku():
    Grid = [[0 for x in range(9)] for y in range(9)]
            
    for i in range(9):
        for j in range(9):
            Grid[i][j] = 0
            
    for i in range(15):
        row = random.randrange(9)
        col = random.randrange(9)
        num = random.randrange(1,10)
        while(not valida_aleatorio(Grid,row,col,num) or Grid[row][col] != 0): 
            row = random.randrange(9)
            col = random.randrange(9)
            num = random.randrange(1,10)
        Grid[row][col]= num;
    return (Grid)

def valida_aleatorio(Grid,row,col,num):
    valid = True
    for x in range(9):
        if (Grid[x][col] == num):
            valid = False
    for y in range(9):
        if (Grid[row][y] == num):
            valid = False
    rowsection = row // 3
    colsection = col // 3
    for x in range(3):
        for y in range(3):
            if(Grid[rowsection*3 + x][colsection*3 + y] == num):
                valid = False
    return valid

In [7]:
aleatorio = gera_sudoku()
print (numpy.array(aleatorio))
Printgrid(aleatorio)

[[0 3 0 8 0 0 0 0 0]
 [0 0 0 4 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 4 0 0]
 [0 4 0 0 2 0 0 8 0]
 [0 0 0 7 0 0 0 0 0]
 [4 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 8 0 1]
 [0 8 0 0 0 0 0 0 0]]
|--------------------------------|
|  0  3  0 |  8  0  0 |  0  0  0 |
|  0  0  0 |  4  0  0 |  0  5  0 |
|  0  0  0 |  0  0  0 |  0  0  3 |
|----------+----------+----------|
|  0  0  0 |  0  0  0 |  4  0  0 |
|  0  4  0 |  0  2  0 |  0  8  0 |
|  0  0  0 |  7  0  0 |  0  0  0 |
|----------+----------+----------|
|  4  0  0 |  0  0  0 |  2  0  0 |
|  0  0  0 |  0  0  0 |  8  0  1 |
|  0  8  0 |  0  0  0 |  0  0  0 |
|--------------------------------|


In [8]:
# Tabuleiros escolhidos previamente
Tab_def = [[5,1,7,6,0,0,0,3,4],
         [2,8,9,0,0,4,0,0,0],
         [3,4,6,2,0,5,0,9,0],
         [6,0,2,0,0,0,0,1,0],
         [0,3,8,0,0,6,0,4,7],
         [0,0,0,0,0,0,0,0,0],
         [0,9,0,0,0,0,0,7,8],
         [7,0,3,4,0,0,5,6,0],
         [0,0,0,0,0,0,0,0,0]]

Tab_def_hard1 = [[0,8,0,4,7,9,0,0,2],
         [0,0,7,0,0,2,0,0,0],
         [0,0,0,5,0,0,0,6,4],
         [2,4,3,0,0,7,0,0,0],
         [8,0,0,9,1,0,0,0,0],
         [0,0,1,0,0,0,0,0,0],
         [6,0,0,3,0,5,0,0,0],
         [0,0,8,0,0,0,0,0,9],
         [3,7,0,0,9,1,2,0,0]]

Tab_def_hard2 = [[0,0,0,0,0,6,0,0,0],
         [9,3,0,5,0,0,0,0,0],
         [0,0,0,0,0,0,8,9,1],
         [0,0,0,0,0,0,0,1,0],
         [5,0,0,4,0,0,0,0,7],
         [0,6,0,9,1,0,2,5,0],
         [0,7,0,0,0,0,5,0,0],
         [2,0,0,0,6,0,4,0,0],
         [8,5,0,0,0,4,0,0,2]]

Tab_def_expert = [[0,0,0,1,0,0,0,7,0],
         [0,3,0,0,0,0,0,6,0],
         [0,0,2,0,6,4,5,0,0],
         [0,0,0,0,0,0,0,4,0],
         [0,5,0,0,0,0,0,0,0],
         [0,0,0,2,0,6,8,9,1],
         [0,0,0,9,0,0,0,0,7],
         [8,6,5,0,2,0,0,0,0],
         [0,0,1,0,0,3,0,0,0]]


<p><b> SENSOR </b></p>

In [9]:
def busca_vazio(grid, i, j):
        for x in range(i,9):
                for y in range(j,9):
                        if grid[x][y] == 0:
                                return x,y
        for x in range(0,9):
                for y in range(0,9):
                        if grid[x][y] == 0:
                                return x,y
        return -1,-1

<p><b> ATUADOR </b></p>

In [10]:
def validacao(grid, i, j, e):
        rowOk = all([e != grid[i][x] for x in range(9)])
        if rowOk:
                columnOk = all([e != grid[x][j] for x in range(9)])
                if columnOk:
                        secTopX, secTopY = 3 *(i//3), 3 *(j//3)  
                        for x in range(secTopX, secTopX+3):
                                for y in range(secTopY, secTopY+3):
                                        if grid[x][y] == e:
                                                return False
                        return True
        return False
def resolucao_sudoku(grid, i=0, j=0):
        i,j = busca_vazio(grid, i, j)
        if i == -1:
                return True
        for e in range(1,10):
                if validacao(grid,i,j,e):
                        grid[i][j] = e 
                        if resolucao_sudoku(grid, i, j):
                                return True, grid
                        grid[i][j] = 0
        return False

<p><b> Testes </b></p>

Tabuleiro gerado aleatoriamente

In [11]:
Printgrid(aleatorio)

|--------------------------------|
|  0  3  0 |  8  0  0 |  0  0  0 |
|  0  0  0 |  4  0  0 |  0  5  0 |
|  0  0  0 |  0  0  0 |  0  0  3 |
|----------+----------+----------|
|  0  0  0 |  0  0  0 |  4  0  0 |
|  0  4  0 |  0  2  0 |  0  8  0 |
|  0  0  0 |  7  0  0 |  0  0  0 |
|----------+----------+----------|
|  4  0  0 |  0  0  0 |  2  0  0 |
|  0  0  0 |  0  0  0 |  8  0  1 |
|  0  8  0 |  0  0  0 |  0  0  0 |
|--------------------------------|


In [12]:
resultadoaleatorio = resolucao_sudoku(aleatorio)
Printgrid(resultadoaleatorio[1])

|--------------------------------|
|  1  3  2 |  8  5  6 |  7  4  9 |
|  6  7  9 |  4  3  2 |  1  5  8 |
|  8  5  4 |  1  7  9 |  6  2  3 |
|----------+----------+----------|
|  9  6  3 |  5  8  1 |  4  7  2 |
|  7  4  1 |  6  2  3 |  9  8  5 |
|  5  2  8 |  7  9  4 |  3  1  6 |
|----------+----------+----------|
|  4  1  5 |  9  6  8 |  2  3  7 |
|  3  9  7 |  2  4  5 |  8  6  1 |
|  2  8  6 |  3  1  7 |  5  9  4 |
|--------------------------------|


Tabuleiros inseridos manualmente

In [13]:
# ========= Dificuldade: normal ==============
Printgrid(Tab_def)

|--------------------------------|
|  5  1  7 |  6  0  0 |  0  3  4 |
|  2  8  9 |  0  0  4 |  0  0  0 |
|  3  4  6 |  2  0  5 |  0  9  0 |
|----------+----------+----------|
|  6  0  2 |  0  0  0 |  0  1  0 |
|  0  3  8 |  0  0  6 |  0  4  7 |
|  0  0  0 |  0  0  0 |  0  0  0 |
|----------+----------+----------|
|  0  9  0 |  0  0  0 |  0  7  8 |
|  7  0  3 |  4  0  0 |  5  6  0 |
|  0  0  0 |  0  0  0 |  0  0  0 |
|--------------------------------|


In [14]:
normal = resolucao_sudoku(Tab_def)
Printgrid(normal[1])

|--------------------------------|
|  5  1  7 |  6  9  8 |  2  3  4 |
|  2  8  9 |  1  3  4 |  7  5  6 |
|  3  4  6 |  2  7  5 |  8  9  1 |
|----------+----------+----------|
|  6  7  2 |  8  4  9 |  3  1  5 |
|  1  3  8 |  5  2  6 |  9  4  7 |
|  9  5  4 |  7  1  3 |  6  8  2 |
|----------+----------+----------|
|  4  9  5 |  3  6  2 |  1  7  8 |
|  7  2  3 |  4  8  1 |  5  6  9 |
|  8  6  1 |  9  5  7 |  4  2  3 |
|--------------------------------|


In [15]:
# ========== Dificuldade: difícil ================
Printgrid(Tab_def_hard1)

|--------------------------------|
|  0  8  0 |  4  7  9 |  0  0  2 |
|  0  0  7 |  0  0  2 |  0  0  0 |
|  0  0  0 |  5  0  0 |  0  6  4 |
|----------+----------+----------|
|  2  4  3 |  0  0  7 |  0  0  0 |
|  8  0  0 |  9  1  0 |  0  0  0 |
|  0  0  1 |  0  0  0 |  0  0  0 |
|----------+----------+----------|
|  6  0  0 |  3  0  5 |  0  0  0 |
|  0  0  8 |  0  0  0 |  0  0  9 |
|  3  7  0 |  0  9  1 |  2  0  0 |
|--------------------------------|


In [16]:
dificil1 = resolucao_sudoku(Tab_def_hard1)
Printgrid(dificil1[1])

|--------------------------------|
|  5  8  6 |  4  7  9 |  1  3  2 |
|  4  3  7 |  1  6  2 |  5  9  8 |
|  9  1  2 |  5  3  8 |  7  6  4 |
|----------+----------+----------|
|  2  4  3 |  6  8  7 |  9  1  5 |
|  8  6  5 |  9  1  3 |  4  2  7 |
|  7  9  1 |  2  5  4 |  6  8  3 |
|----------+----------+----------|
|  6  2  9 |  3  4  5 |  8  7  1 |
|  1  5  8 |  7  2  6 |  3  4  9 |
|  3  7  4 |  8  9  1 |  2  5  6 |
|--------------------------------|


In [17]:
# ============ Dificuldade: expert ==============
Printgrid(Tab_def_expert)

|--------------------------------|
|  0  0  0 |  1  0  0 |  0  7  0 |
|  0  3  0 |  0  0  0 |  0  6  0 |
|  0  0  2 |  0  6  4 |  5  0  0 |
|----------+----------+----------|
|  0  0  0 |  0  0  0 |  0  4  0 |
|  0  5  0 |  0  0  0 |  0  0  0 |
|  0  0  0 |  2  0  6 |  8  9  1 |
|----------+----------+----------|
|  0  0  0 |  9  0  0 |  0  0  7 |
|  8  6  5 |  0  2  0 |  0  0  0 |
|  0  0  1 |  0  0  3 |  0  0  0 |
|--------------------------------|


In [18]:
expert = resolucao_sudoku(Tab_def_expert)
Printgrid(expert[1])

|--------------------------------|
|  5  8  6 |  1  3  2 |  4  7  9 |
|  4  3  7 |  5  9  8 |  1  6  2 |
|  9  1  2 |  7  6  4 |  5  3  8 |
|----------+----------+----------|
|  6  2  9 |  8  7  1 |  3  4  5 |
|  1  5  8 |  3  4  9 |  7  2  6 |
|  3  7  4 |  2  5  6 |  8  9  1 |
|----------+----------+----------|
|  2  4  3 |  9  1  5 |  6  8  7 |
|  8  6  5 |  4  2  7 |  9  1  3 |
|  7  9  1 |  6  8  3 |  2  5  4 |
|--------------------------------|
